### ISSUE TITLE
article page cannot scroll

### ISSUE THREAD

**Issue by szqingt** [Nauxscript/nauxscript.me#14]
the cause maybe is overflow-hidden 🤔 
https://github.com/Nauxscript/nauxscript.me/blob/206511d083174b24b1f79c00a6f70742505acb30/src/layouts/Layout.astro#L32

**Comment by Nauxscript** [comment]
Thanks for your feedback 😂! I'll be addressing that issue soon. The article page is still a work in progress as I'm still figuring out its design. Meanwhile, I really appreciate your visit to my blog 😁!
